version: '3'
services:
  server:
    image: node
    container_name: clipboard-api
    working_dir: /api
    volumes:
      - ./api:/api
    command: npm start
    ports:
      - "4000:4000"
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
